name: LINUX_OS_TEST_DOCKER

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download docker
        run: |
          docker pull debian:bookworm
          docker create --name x-000 --privileged -e "INCLUDE_PACKAGE=apt-utils,bash-completion,locales,whiptail" -v $(pwd):/xxx --entrypoint "tail" debian:bookworm "-f" "/dev/null"

      - name: exec
        run: |
           c_name=x-000
           docker start $c_name
           docker exec $c_name mkdir -p /xxx/rootfs
           docker exec $c_name apt update
           docker exec $c_name apt install debootstrap -y
           docker exec $c_name debootstrap --variant=minbase --arch X86_64 --include=apt-utils,bash-completion,locales,whiptail bookworm /xxx/rootfs http://deb.debian.org/debian
           docker exec $c_name ls -la rootfs
