name: LINUX_OS_TEST_DOCKER

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download docker
        run: |
          docker pull debian:bookworm
          docker create --name x-000 --privileged -v $(pwd):/xxx --entrypoint "tail" debian:bookworm "-f" "/dev/null"

      - name: exec
        run: |
           c_name=x-000
           docker start $c_name
           docker exec $c_name mkdir -p /xxx/abc
           ls -A
