name: LINUX_OS_TEST_DOCKER

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download docker
        run: |
          docker pull debian:bookworm
          docker create --name x-000 --privileged -e "INCLUDE_PACKAGE=apt-utils,bash-completion,locales,whiptail" -v $(pwd):/xxx --entrypoint "tail" debian:bookworm "-f" "/dev/null"

      - name: exec
        run: |
           c_name=x-000
           docker start $c_name
           docker exec $c_name mkdir -p /xxx/rootfs
           docker exec $c_name apt update
           docker exec $c_name apt install debootstrap -y
           docker exec $c_name debootstrap --variant=minbase --arch amd64 --exclude=e2fsprogs,sysvinit-utils,ncurses-base,ncurses-bin,mawk --include=apt-utils,bash-completion,locales,whiptail bookworm /xxx/rootfs http://deb.debian.org/debian
           sudo chroot rootfs /bin/bash <<"EOF_CHROOT"
           # SETUP LOCALES
           echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
           dpkg-reconfigure --frontend=noninteractive locales
           update-locale LANG=en_US.UTF-8
          
           # REINSTALL ALL PACKAGE
           export DEBIAN_FRONTEND=noninteractive
           apt update
           #packages=$(dpkg --get-selections | grep -v deinstall | awk '{print $1}')
           #apt install --no-install-recommends --no-install-suggests --reinstall $packages -y
           #echo "$packages" | wc -l
           EOF_CHROOT
           # CHROOT END
