name: WINDOWS_OS

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Window Version
        run: |
          systeminfo